name: Debug

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Use yarn berry
        run: yarn set version berry
      - name: Install node-pqclean
        run: yarn add pqclean
